-
  version: 2.1.{build}

  branches:
    only:
      - master

  skip_tags: true

  init:
    - git config --global core.autocrlf input

  clone_folder: C:\projects\vlc-dotnet-master\

  shallow_clone: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.1.{build}"
    assembly_file_version: "2.1.0.0"
    assembly_informational_version: "2.1.0.0"

  build_script:
    - msbuild "src\Vlc.DotNet.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release;Platform=AnyCPU
    - ps: 7z a "C:\projects\vlc-dotnet-master\Vlc.DotNet for Vlc 2.1.x - AnyCPU - .Net 2.0.zip" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core\Release - AnyCPU - .Net 2.0\Vlc.DotNet.Core.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core.Interops\Release - AnyCPU - .Net 2.0\Vlc.DotNet.Core.Interops.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Forms\Release - AnyCPU - .Net 2.0\Vlc.DotNet.Forms.dll"
    - ps: 7z a "C:\projects\vlc-dotnet-master\Vlc.DotNet for Vlc 2.1.x - AnyCPU - .Net 3.5.zip" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core\Release - AnyCPU - .Net 3.5\Vlc.DotNet.Core.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core.Interops\Release - AnyCPU - .Net 3.5\Vlc.DotNet.Core.Interops.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Forms\Release - AnyCPU - .Net 3.5\Vlc.DotNet.Forms.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Wpf\Release - AnyCPU - .Net 3.5\Vlc.DotNet.Wpf.dll"
    - ps: 7z a "C:\projects\vlc-dotnet-master\Vlc.DotNet for Vlc 2.1.x - AnyCPU - .Net 4.0.zip" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core\Release - AnyCPU - .Net 4.0\Vlc.DotNet.Core.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core.Interops\Release - AnyCPU - .Net 4.0\Vlc.DotNet.Core.Interops.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Forms\Release - AnyCPU - .Net 4.0\Vlc.DotNet.Forms.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Wpf\Release - AnyCPU - .Net 4.0\Vlc.DotNet.Wpf.dll"
    - ps: 7z a "C:\projects\vlc-dotnet-master\Vlc.DotNet for Vlc 2.1.x - AnyCPU - .Net 4.5.zip" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core\Release - AnyCPU - .Net 4.5\Vlc.DotNet.Core.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Core.Interops\Release - AnyCPU - .Net 4.5\Vlc.DotNet.Core.Interops.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Forms\Release - AnyCPU - .Net 4.5\Vlc.DotNet.Forms.dll" "C:\projects\vlc-dotnet-master\build\Vlc.DotNet.Wpf\Release - AnyCPU - .Net 4.5\Vlc.DotNet.Wpf.dll"
    - ps: (Get-Content 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.Interops.nuspec') | Foreach-Object {$_ -replace '\$version\$',$env:APPVEYOR_BUILD_VERSION}  | Out-File 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.Interops.nuspec'
    - ps: (Get-Content 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.nuspec') | Foreach-Object {$_ -replace '\$version\$',$env:APPVEYOR_BUILD_VERSION}  | Out-File 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.nuspec'
    - ps: (Get-Content 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Forms.nuspec') | Foreach-Object {$_ -replace '\$version\$',$env:APPVEYOR_BUILD_VERSION}  | Out-File 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Forms.nuspec'
    - ps: (Get-Content 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Wpf.nuspec') | Foreach-Object {$_ -replace '\$version\$',$env:APPVEYOR_BUILD_VERSION}  | Out-File 'C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Wpf.nuspec'
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.Interops.nuspec
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.nuspec
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Forms.nuspec
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Wpf.nuspec
    - ps: 7z a "C:\projects\vlc-dotnet-master\nuget-packages.zip" *.nupkg

  artifacts:
    - path: "**/*.zip"
      name: "Vlc.DotNet for Vlc 2.1.x"
    - path: "**/*.nupkg"
      name: "Vlc.DotNet for Vlc 2.1.x NuGet Packages"

  deploy:
    - provider: NuGet
      api_key:
          secure: OriZXhNZQOSzNsBXQsoUBOScm5K9AJ9HLZBGL+Gcsrj5VcVCAXpA1Rv3vaGHmnRE
      artifact: /.*\.nupkg/

-
  version: 2.2.0-develop{build}

  branches:
    only:
      - develop

  skip_tags: true

  init:
    - git config --global core.autocrlf input

  clone_folder: C:\projects\vlc-dotnet-master\

  shallow_clone: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.2.0"
    assembly_file_version: "2.2.0.0"
    assembly_informational_version: "2.2.0.0"

  build_script:
    - msbuild "src\Vlc.DotNet.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release;Platform=AnyCPU
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.Interops.nuspec -version $env:APPVEYOR_BUILD_VERSION
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Core.nuspec -version $env:APPVEYOR_BUILD_VERSION
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Forms.nuspec -version $env:APPVEYOR_BUILD_VERSION
    - ps: nuget pack C:\projects\vlc-dotnet-master\nuget\Vlc.DotNet.Wpf.nuspec -version $env:APPVEYOR_BUILD_VERSION

  artifacts:
    - path: "**/*.nupkg"
      name: "Vlc.DotNet NuGet Packages"

  deploy:
    - provider: NuGet
      api_key:
          secure: OriZXhNZQOSzNsBXQsoUBOScm5K9AJ9HLZBGL+Gcsrj5VcVCAXpA1Rv3vaGHmnRE
      artifact: /.*\.nupkg/
